server:
  port: 8086
spring:
  datasource:
    username: root
    password: Star*2018
    url: jdbc:mysql://47.104.159.8:3306/nowcode?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 47.104.159.8
    port: 6379
    password: 158320
    database: 0
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.nowcoder.testmybatis.entity
