server:
  port: 8081
spring:
  datasource:
    username: ytg
    password: Star*2018
    url: jdbc:mysql://47.104.159.8:3306/blog?characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 47.104.159.8
    port: 6379
    password: 158320
    database: 0
    lettuce:
      pool:
        max-active: 100
  cache:
    type: redis
